--- #YAML:1.0
name:                WWW-Twitpic
version:             0.01
abstract:            Use the twitpic.com simple API from our favorite language.
license:             ~
author:              
    - Diego Kuperman <diego@freekeylabs.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTTP::Request::Common:         0
    LWP::UserAgent:                0
    Moose:                         0
    Moose::Util::TypeConstraints:  0
    Test::More:                    0
    URI:                           0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
